apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-app-deployment # Define the Deployment Name
  namespace: DEPLOYMENTENVIRONMENT
spec:
  selector: # Define the Selector
    matchLabels:
      run: python-flask-app-label
      appversion: BUILDNUMBER
  replicas: 2 # Define the Number of Pods
  template:
    metadata:
      labels:
        run: python-flask-app-label
        appversion: BUILDNUMBER
    spec:
      containers: # Container Details
      - name: python-flask-app-container
        image: nishanthkp/python-flask-app:TAG
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred
---

apiVersion: v1
kind: Service
metadata:
  name: python-flask-app-service
  namespace: DEPLOYMENTENVIRONMENT
  labels:
    run: python-flask-app-label
    appversion: BUILDNUMBER
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    run: python-flask-app-label
    appversion: BUILDNUMBER